/**
 * item-contract
 * item
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDto } from './userResponseDto';
import { ReviewType } from './reviewType';


export interface ReviewResponseDto { 
    id?: string;
    message?: string;
    postedBy?: UserResponseDto;
    receiver?: string;
    reviewType?: ReviewType;
}

