/**
 * user-generated-contract
 * user-generated-contract
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Currency } from './currency';


export interface TattooArtistPriceInterval { 
    maxTattooWorkPrice?: number;
    minTattooWorkPrice?: number;
    minTattooWorkPriceCurrency?: Currency;
    maxTattooWorkPriceCurrency?: Currency;
}

