/**
 * tattoo-work-contract
 * tattoo-work
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Currency } from './currency';


export interface TattooWorkPostRequestDto { 
    description?: string;
    price?: number;
    currency?: Currency;
    coverPhoto?: string;
    photos?: Array<string>;
    clientId?: string;
    madeById?: string;
}

