/**
 * Tattoo-Work Contract
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MadeByInfo } from './madeByInfo';
import { Currency } from './currency';
import { TattooStyle } from './tattooStyle';


export interface TattooWorksResponseDto { 
    id?: string;
    description?: string;
    clientId?: string;
    price?: number;
    commentId?: string;
    currency?: Currency;
    dislike_number?: number;
    like_number?: number;
    coverPhoto?: string;
    photos?: Array<string>;
    madeBy?: MadeByInfo;
    disLikerIds?: Array<string>;
    likerIds?: Array<string>;
    tattooStyle?: TattooStyle;
}

