/**
 * Tattoo-Work Contract
 * Title
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TattooWorkReportResDto } from './tattooWorkReportResDto';


export interface TattooWorkReportResPageable { 
    totalPages?: number;
    totalElements?: number;
    tattooWorkReports?: Array<TattooWorkReportResDto>;
}

