openapi: 3.0.3
info:
  title: item-contract
  description: item
  version: 1.0.0
paths:
  /reviews/{id}:
    get:
      operationId: getReviewsById
      description: get revie
      parameters:
        - in: path
          name: id
          description: reviewId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewResponseDto'
        default:
          description: error payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      security:
        - bearerAuth: [ ]
      operationId: deleteReviewById
      description: delete review
      parameters:
        - in: path
          name: id
          description: reviewId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: no content
        default:
          description: error payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      security:
        - bearerAuth: [ ]
      operationId: reviewPatchUpdate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewPatchRequestDto'
      parameters:
        - in: path
          name: id
          description: reviewId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewResponseDto'
        default:
          description: error payload
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/ErrorResponse'


  /reviews/users/{receiver_id}:
    post:
      operationId: createReview
      description: post review for tattooArtist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewPostRequestDto'
      parameters:
        - in: path
          name: receiver_id
          description: receiverId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/ReviewResponseDto'
        default:
          description: error payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      operationId: getAllReviewByUserId
      description: get all
      parameters:
        - in: path
          name: receiver_id
          description: receiverId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReviewResponseDto'
        default:
          description: error payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ReviewPatchRequestDto:
      type: object
      properties:
        message:
          type: string
        reviewType:
          $ref: "#/components/schemas/ReviewType"

    ReviewPostRequestDto:
      type: object
      properties:
        message:
          type: string
        postedBy:
          type: string
          format: uuid
        reviewType:
          $ref: "#/components/schemas/ReviewType"

    ReviewResponseDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        message:
          type: string
        postedBy:
          $ref: "#/components/schemas/UserResponseDto"
        receiver:
          type: string
          format: uuid
        reviewType:
          $ref: "#/components/schemas/ReviewType"

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

    ReviewType:
      enum:
        - POSITIVE
        - NEGATIVE
        - NEUTRAL
    UserResponseDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        uid:
          type: string
          description: id for firebase auth
        firstName:
          type: string
        lastName:
          type: string
        avatarUrl:
          type: string
        birthDate:
          type: string
          format: date
        email:
          type: string
        hasArtistPage:
          type: boolean
        workDays:
          type: array
          items:
            $ref: '#/components/schemas/WorkingDays'
        averageRating:
          type: number
        phoneNumber:
          type: string
        street:
          type: string
        city:
          type: string
        country:
          type: string
        state:
          type: string
        postalCode:
          type: string
        otherInformation:
          type: string
        favoriteArtistIds:
          type: array
          items:
            type: string
            format: uuid
        favoriteTattooWorkIds:
          type: array
          items:
            type: string
            format: uuid
        commentIds:
          type: array
          items:
            type: string
            format: uuid
        tattooWorkIds:
          type: array
          items:
            type: string
            format: uuid
